## Loops

For and while loops!

In [1]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


can also use = or element sign instead of in above

### make an addition table

In [8]:
m,n = 5,5
A = zeros(5,5)

for i in 1:m
    for j in 1:n
        A[i,j] = i+j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [12]:
B = zeros(5,5)
for i in 1:m, j in 1:n
        B[i,j] = i+j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [14]:
# without pre initialisation
C = [i+j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [15]:
for n in 1:10
    A = [i+j for i in 1:n, j in 1:m]
    display(A)
end

1×5 Array{Int64,2}:
 2  3  4  5  6

2×5 Array{Int64,2}:
 2  3  4  5  6
 3  4  5  6  7

3×5 Array{Int64,2}:
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8

4×5 Array{Int64,2}:
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8
 5  6  7  8  9

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×5 Array{Int64,2}:
 2  3  4   5   6
 3  4  5   6   7
 4  5  6   7   8
 5  6  7   8   9
 6  7  8   9  10
 7  8  9  10  11

7×5 Array{Int64,2}:
 2  3   4   5   6
 3  4   5   6   7
 4  5   6   7   8
 5  6   7   8   9
 6  7   8   9  10
 7  8   9  10  11
 8  9  10  11  12

8×5 Array{Int64,2}:
 2   3   4   5   6
 3   4   5   6   7
 4   5   6   7   8
 5   6   7   8   9
 6   7   8   9  10
 7   8   9  10  11
 8   9  10  11  12
 9  10  11  12  13

9×5 Array{Int64,2}:
  2   3   4   5   6
  3   4   5   6   7
  4   5   6   7   8
  5   6   7   8   9
  6   7   8   9  10
  7   8   9  10  11
  8   9  10  11  12
  9  10  11  12  13
 10  11  12  13  14

10×5 Array{Int64,2}:
  2   3   4   5   6
  3   4   5   6   7
  4   5   6   7   8
  5   6   7   8   9
  6   7   8   9  10
  7   8   9  10  11
  8   9  10  11  12
  9  10  11  12  13
 10  11  12  13  14
 11  12  13  14  15

### If statements

In [23]:
x=5
y=50

50

In [20]:
if x>y
    println("$x is greater than $y")
elseif x<y
    println("$y is greater than $x")
else
    println("$x and $y are equal")
end

5 and 5 are equal


In [21]:
# return larger number
if x>y
    x
elseif y>x
    y
else
    x
end


5

### ternary operators

a ? b : c

where a is a conditional and b and c are outputs:

In [24]:
(x>y) ? x : y

50

In [25]:
# short circuit evaluation
(x>y) && println("$x is greater than $y")

false

In [26]:
(x<y) && println("$y is greater than $x")

50 is greater than 5
